config/routes.rb
Rails.application.routes.draw do
  resources :instagram_user_profiles
  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new', as: 'login'
  get 'sessions/create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  resources :posts do
    resources :comments , only: [:create, :destroy]
  end
  root to:'posts#index'
  namespace :api, default: { format: 'json' } do
    get 'posts/search', to: 'posts#search'
    resources :posts
  end
  namespace :api, default: { format: 'json' } do
    resources :instagram_user_profiles
  end
  namespace :api, default: { format: 'json' } do
    post '/login', to: 'sessions#create'
    resources :sessions
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :api_keys, as: :bearer
  has_secure_password
  has_many :posts
  has_one :user_profile
end

app/controllers/user/private_api_keys_controller.rb
class User::PrivateApiKeysController < ApplicationController
  before_action :authenticate_user!

  def update
    if current_user.update(private_api_key: SecureRandom.hex)
      redirect_to edit_user_registration_path, notice: "API Updated"
    else
      redirect_to edit_user_registration_path, alert: "There was an error: #{current_user.errors.full_messages.to_sentence}"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice]="Signup successful"
    else
      flash[:notice]="Please try again"
      redirect_to '/signup'
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:user_name, :first_name, :last_name, :email_address, :phone_number, :password)
    end
end

app/helpers/user/private_api_keys_helper.rb
module User::PrivateApiKeysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_name, style: "display: block" %>
    <%= form.text_field :user_name %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email_address, style: "display: block" %>
    <%= form.text_field :email_address %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>User name:</strong>
    <%= user.user_name %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email address:</strong>
    <%= user.email_address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= user.phone_number %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= form_for :user, url: '/users' do |f|%>
  <div>
    <%= f.text_field :user_name, :placeholder => "User Name" %>
    <%= f.text_field :first_name, :placeholder => "First Name" %>
    <%= f.text_field :last_name, :placeholder => "Last Name" %>
    <%= f.phone_field :phone_number, :placeholder => "Phone number" %>
    <%= f.email_field :email_address, :placeholder => "Email" %>
    <%= f.password_field :password_digest, :placeholder => "Password" %>
    <%= f.submit "Create an account", class: "btn-submit" %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="userProfile-container">
  <div class="profile">
    <div class="profileImage">
      <%= image_tag url_for(@user_profile.avatar), size: "600x400" %>
      <br>
    </div>
    <div class="edit-UserProfile">
      <%= button_to "Edit Profile", edit_user_profile_path(@user_profile) %>
    </div>
    <div class="profile-bio">
      <p><%= @user_profile.bio %></p>
    </div>
  </div>
</div>

<div>
  <%= link_to "Back to user profiles", user_profiles_path %>

  <%= button_to "Destroy this user profile", @user_profile, method: :delete %>
</div>