config/routes.rb
Rails.application.routes.draw do
  resources :instagram_user_profiles
  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new', as: 'login'
  get 'sessions/create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  resources :posts do
    resources :comments , only: [:create, :destroy]
  end
  root to:'posts#index'
  namespace :api, default: { format: 'json' } do
    get 'posts/search', to: 'posts#search'
    resources :posts
  end
  namespace :api, default: { format: 'json' } do
    resources :instagram_user_profiles
  end
  namespace :api, default: { format: 'json' } do
    post '/login', to: 'sessions#create'
    resources :sessions
  end
end

app/models/instagram_user_profile.rb
class InstagramUserProfile < ApplicationRecord
  has_one_attached :avatar
end

app/controllers/api/instagram_user_profiles_controller.rb
class Api::InstagramUserProfilesController < ApiController
  def index
    render json: InstagramUserProfile.all
  end

  def show
    instagram_user_profile = InstagramUserProfile.find_by(id: params[:id])
    if instagram_user_profile
      render json: instagram_user_profile,status: 200
    else
      render json: { error: 'Profile not found'}, status: 404
    end
  end

  def destroy
    InstagramUserProfile.destroy(id: params[:id])
    render :show, status: :ok
  end
end

app/controllers/instagram_user_profiles_controller.rb
class InstagramUserProfilesController < ApplicationController
  before_action :set_instagram_user_profile, only: %i[ show edit update destroy ]

  # GET /instagram_user_profiles or /instagram_user_profiles.json
  def index
    @instagram_user_profiles = InstagramUserProfile.all
  end

  # GET /instagram_user_profiles/1 or /instagram_user_profiles/1.json
  def show
  end

  # GET /instagram_user_profiles/new
  def new
    @instagram_user_profile = InstagramUserProfile.new
  end

  # GET /instagram_user_profiles/1/edit
  def edit
  end

  # POST /instagram_user_profiles or /instagram_user_profiles.json
  def create
    @instagram_user_profile = InstagramUserProfile.new(instagram_user_profile_params)

    respond_to do |format|
      if @instagram_user_profile.save
        format.html { redirect_to instagram_user_profile_url(@instagram_user_profile), notice: "Instagram user profile was successfully created." }
        format.json { render :show, status: :created, location: @instagram_user_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instagram_user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instagram_user_profiles/1 or /instagram_user_profiles/1.json
  def update
    respond_to do |format|
      if @instagram_user_profile.update(instagram_user_profile_params)
        format.html { redirect_to instagram_user_profile_url(@instagram_user_profile), notice: "Instagram user profile was successfully updated." }
        format.json { render :show, status: :ok, location: @instagram_user_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instagram_user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instagram_user_profiles/1 or /instagram_user_profiles/1.json
  def destroy
    @instagram_user_profile.destroy

    respond_to do |format|
      format.html { redirect_to instagram_user_profiles_url, notice: "Instagram user profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instagram_user_profile
      @instagram_user_profile = InstagramUserProfile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instagram_user_profile_params
      params.require(:instagram_user_profile).permit(:avatar, :bio)
    end
end

app/helpers/instagram_user_profiles_helper.rb
module InstagramUserProfilesHelper
end

app/views/instagram_user_profiles/_form.html.erb
<%= form_with(model: instagram_user_profile) do |form| %>
  <% if instagram_user_profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(instagram_user_profile.errors.count, "error") %> prohibited this instagram_user_profile from being saved:</h2>

      <ul>
        <% instagram_user_profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :avatar, style: "display: block" %>
    <%= form.text_field :avatar %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_field :bio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/instagram_user_profiles/_instagram_user_profile.html.erb
<div id="<%= dom_id instagram_user_profile %>">
  <p>
    <strong>Avatar:</strong>
    <%= instagram_user_profile.avatar %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= instagram_user_profile.bio %>
  </p>

</div>

app/views/instagram_user_profiles/edit.html.erb
<h1>Editing instagram user profile</h1>

<h1>Editing post</h1>

<div class="edit-post-form">
  <%= form_for @instagram_user_profile do |user_profile| %>
    <%= user_profile.label :"Edit profile image of the user" %><br>
    <br>
    <%= user_profile.file_field :avatar %><br>
    <br>
    <%= user_profile.label :"Edit bio of the user" %><br>
    <br>
    <%= user_profile.text_field :bio %><br>
    <br>
    <%= user_profile.button "Update User Profile", type: "submit" %>
  <% end %>
</div>

<br>

<div>
  <%= link_to "Show this instagram user profile", @instagram_user_profile %> |
  <%= link_to "Back to instagram user profiles", instagram_user_profiles_path %>
</div>

app/views/instagram_user_profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<br>
<br>
<br>
<h1 class="">Instagram user profile</h1>

<div id="instagram_user_profiles">
  <% if @instagram_user_profiles.present? %>
    <% @instagram_user_profiles.each do |instagram_user_profile| %>
      <div class="userProfile-container">
        <div class="profile">
          <div class="profileImage">
            <p>Profile Image : </p>
            <%= image_tag url_for(instagram_user_profile.avatar), size: "360x360" %>
            <br>
            <div class="profile-bio">
              <p>User Profile Bio : </p>
              <p><%= instagram_user_profile.bio %></p>
            </div>
          </div>
        </div>
      </div>
      <p>
        <%= link_to "Show this instagram user profile", instagram_user_profile %>
      </p>
    <% end %>
  <% else %>
    <%= link_to "New instagram user profile", new_instagram_user_profile_path %>
  <% end %>
</div>

<%= button_to "Back to Posts", posts_path, method: :get %>

app/views/instagram_user_profiles/new.html.erb
<h1>New user profile</h1>

<%= form_for @instagram_user_profile do |user_profile| %>
  <%= user_profile.label :"Upload your profile photo" %> <br>
  <br>
  <%= user_profile.file_field :avatar %> <br>
  <br>
  <%= user_profile.label :"Update your bio" %> <br>
  <br>
  <%= user_profile.text_field :bio %> <br>
  <br>
  <%= user_profile.button "Create User Profile", type: "submit" %>
<% end %>

<br>

<div>
  <%= link_to "Back to user profiles", instagram_user_profiles_path %>
</div>

app/views/instagram_user_profiles/show.html.erb
<p style="color: green"><%= notice %></p>
<br>
<br>
<h1>Instagram User Profile</h1>
<br>
<br>
<div class="userProfile-container">
  <div class="profile">
    <div class="profileImage">
      <p>Profile Image : </p>
      <%= image_tag url_for(@instagram_user_profile.avatar), size: "360x360" %>
      <br>
      <div class="profile-bio">
        <p>User Profile Bio : </p>
        <p><%= @instagram_user_profile.bio %></p>
      </div>
    </div>
    <div class="edit-UserProfile">
      <%= button_to "Edit Profile", edit_instagram_user_profile_path(@instagram_user_profile) %>
    </div>
  </div>
</div>

<div>
  <%= link_to "Edit this instagram user profile", edit_instagram_user_profile_path(@instagram_user_profile) %> |
  <%= link_to "Back to instagram user profile", instagram_user_profiles_path %>
  <%= button_to "Delete this instagram user profile", @instagram_user_profile, method: :delete %>
</div>