config/routes.rb
Rails.application.routes.draw do
  resources :instagram_user_profiles
  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new', as: 'login'
  get 'sessions/create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  resources :posts do
    resources :comments , only: [:create, :destroy]
  end
  root to:'posts#index'
  namespace :api, default: { format: 'json' } do
    get 'posts/search', to: 'posts#search'
    resources :posts
  end
  namespace :api, default: { format: 'json' } do
    resources :instagram_user_profiles
  end
  namespace :api, default: { format: 'json' } do
    post '/login', to: 'sessions#create'
    resources :sessions
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :post_image
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApiController
  before_action :set_post, only: [:show, :update, :destroy]
  def index
    render json: Post.all
  end

  def show
    post = Post.find_by(id: params[:id])
    if post
      render json: post, include: :comments,status: 200
    else
      render json: { error: 'Post not found'}, status: 404
    end
  end

  def create
    user = User.find(params[:user_id])
    post = user.posts.new(caption: params[:caption])
    if post.save
      render json: post
    else
      render json: { error: 'Cannot create Post'}, status: 404
    end
  end

  def update
    if @post.update(post_params)
      render show, status: '200 OK'
    else
      render json: { message: @post.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def search
    render json: Post.where('caption LIKE ?', "%#{params[:caption]}")
  end

  def destroy
    @post.destroy
    render :show, status: :ok
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:caption)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        PostMailer.with(user: @user).new_post_email.deliver_later
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = current_user.posts.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit( :caption)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :post_image, style: "display: block" %>
    <%= form.file_field :post_image %>
  </div>

  <div>
    <%= form.label :caption, style: "display: block" %>
    <%= form.text_field :caption %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Post image:</strong>
    <%= post.post_image %>
  </p>

  <p>
    <strong>Caption:</strong>
    <%= post.caption %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<div class="edit-post-form">
  <%= form_for @post do |post| %>
    <%= post.label :"Edit image of the post" %><br>
    <br>
    <%= post.file_field :post_image %><br>
    <br>
    <%= post.label :"Edit caption of the post" %><br>
    <br>
    <%= post.text_field :caption %><br>
    <br>
    <%= post.button "Update Post", type: "submit" %>
  <% end %>
</div>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<br>
<br>
<h1 class="post-header">Posts</h1>

<div class="user-profile-container">
  <div class="user-profile">
    <%= button_to 'User Profile', instagram_user_profiles_path, method: :get %>
  </div>
</div>

<div class="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <%= "Post created (#{time_ago_in_words post.created_at} ago)" %>
    <br>
    <%= "Post updated (#{time_ago_in_words post.updated_at} ago)" %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<div class="new-post-btn">
  <%= link_to "New post", new_post_path %>
</div>

app/views/posts/new.html.erb
<br>
<br>
<br>

<h1 class="new-post">Create a new post</h1>

<div class="new-post-form">
  <%= form_for @post do |post| %>
    <%= post.label :"Upload photo to post", style: "display: block" %> <br>
    <br>
    <%= post.file_field :post_image %> <br>
    <br>
    <%= post.label :"Upload caption to your post", style: "display: block" %> <br>
    <br>
    <%= post.text_field :caption %> <br>
    <br>
    <%= post.button "Create New Post", type: "submit" %>
  <% end %>
</div>

<br>

<div class="back-posts-btn">
  <%= button_to "Back to posts", posts_path, method: :get %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<br>
<br>
<br>
<br>
<br>
<h1>Showing User Posts</h1>
<div class="user-post">
  <div class="post-image">
    <% if @post.post_image.attached? %>
      <%= image_tag url_for(@post.post_image), size: "360x360" %>
    <% end %>
  </div>
  <div class="post-caption">
    Caption :
    <%= @post.caption %>
  </div>
  <div>
    <%= "Post created (#{time_ago_in_words @post.created_at} ago)" %>
    <br>
    <%= "Post updated (#{time_ago_in_words @post.updated_at} ago)" %>
  </div>
</div>

<div class="comment-on-post">
  <p>Comment : </p>
</div>

<div id="comments">
  <%= render @post.comments %>
</div>

<div class="comment-section">
  <%= form_for([@post, @post.comments.new]) do |form| %>
    <div>
      <%= form.label :'Comment : ' %> <br>
      <br>
      <%= form.text_field :comment_text %> <br>
      <br>
    </div>
    <div class="add-comment-submit-btn">
      <%= form.button 'Add comment to the Post', type: "submit" %>
    </div>
  <% end %>
</div>

<br>
<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, :data => { :confirm => 'Are you sure ?' },method: :delete %>
</div>